[tool.black]
line-length = 100
target-version = ["py311", "py312"]
exclude = [
  "^/alembic/",
  "^/.venv/",
  "^/frontend/",
]

[tool.ruff]
target-version = "py311"
line-length = 100
indent-width = 4
extend-exclude = [
  "alembic",
  ".venv",
  "frontend",
]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "W",  # warnings
]
ignore = [
]

[tool.ruff.isort]
force-single-line = false
known-first-party = ["backend"]
combine-as-imports = true
